// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: subscription.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartedAt     string                 `protobuf:"bytes,3,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	Expiration    string                 `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subscription) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Subscription) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

func (x *Subscription) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Period struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Period) Reset() {
	*x = Period{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *Period) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Period) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartedAt     string                 `protobuf:"bytes,3,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	Expiration    string                 `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSubscriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           *Subscription          `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSubscriptionResponse) GetSub() *Subscription {
	if x != nil {
		return x.Sub
	}
	return nil
}

type GetSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubscriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           *Subscription          `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *GetSubscriptionResponse) GetSub() *Subscription {
	if x != nil {
		return x.Sub
	}
	return nil
}

type UpdateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartedAt     string                 `protobuf:"bytes,3,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	Expiration    string                 `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionRequest) Reset() {
	*x = UpdateSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionRequest) ProtoMessage() {}

func (x *UpdateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSubscriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           *Subscription          `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionResponse) Reset() {
	*x = UpdateSubscriptionResponse{}
	mi := &file_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionResponse) ProtoMessage() {}

func (x *UpdateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSubscriptionResponse) GetSub() *Subscription {
	if x != nil {
		return x.Sub
	}
	return nil
}

type DeleteSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSubscriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionResponse) Reset() {
	*x = DeleteSubscriptionResponse{}
	mi := &file_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionResponse) ProtoMessage() {}

func (x *DeleteSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Period        *Period                `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsRequest) Reset() {
	*x = GetAnalyticsRequest{}
	mi := &file_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsRequest) ProtoMessage() {}

func (x *GetAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *GetAnalyticsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAnalyticsRequest) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

type GetAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subs          []*Subscription        `protobuf:"bytes,1,rep,name=subs,proto3" json:"subs,omitempty"`
	SummarySpend  int32                  `protobuf:"varint,2,opt,name=summarySpend,proto3" json:"summarySpend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsResponse) Reset() {
	*x = GetAnalyticsResponse{}
	mi := &file_subscription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsResponse) ProtoMessage() {}

func (x *GetAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{11}
}

func (x *GetAnalyticsResponse) GetSubs() []*Subscription {
	if x != nil {
		return x.Subs
	}
	return nil
}

func (x *GetAnalyticsResponse) GetSummarySpend() int32 {
	if x != nil {
		return x.SummarySpend
	}
	return 0
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\"\x86\x01\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tstartedAt\x18\x03 \x01(\tR\tstartedAt\x12\x1e\n" +
	"\n" +
	"expiration\x18\x04 \x01(\tR\n" +
	"expiration\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\"0\n" +
	"\x06Period\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\"\x93\x01\n" +
	"\x19CreateSubscriptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tstartedAt\x18\x03 \x01(\tR\tstartedAt\x12\x1e\n" +
	"\n" +
	"expiration\x18\x04 \x01(\tR\n" +
	"expiration\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\"=\n" +
	"\x1aCreateSubscriptionResponse\x12\x1f\n" +
	"\x03sub\x18\x01 \x01(\v2\r.SubscriptionR\x03sub\"<\n" +
	"\x16GetSubscriptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\":\n" +
	"\x17GetSubscriptionResponse\x12\x1f\n" +
	"\x03sub\x18\x01 \x01(\v2\r.SubscriptionR\x03sub\"\x93\x01\n" +
	"\x19UpdateSubscriptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tstartedAt\x18\x03 \x01(\tR\tstartedAt\x12\x1e\n" +
	"\n" +
	"expiration\x18\x04 \x01(\tR\n" +
	"expiration\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\"=\n" +
	"\x1aUpdateSubscriptionResponse\x12\x1f\n" +
	"\x03sub\x18\x01 \x01(\v2\r.SubscriptionR\x03sub\"?\n" +
	"\x19DeleteSubscriptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\x1aDeleteSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x13GetAnalyticsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\x06period\x18\x02 \x01(\v2\a.PeriodR\x06period\"]\n" +
	"\x14GetAnalyticsResponse\x12!\n" +
	"\x04subs\x18\x01 \x03(\v2\r.SubscriptionR\x04subs\x12\"\n" +
	"\fsummarySpend\x18\x02 \x01(\x05R\fsummarySpend2\x85\x03\n" +
	"\x13SubscriptionService\x12M\n" +
	"\x12CreateSubscription\x12\x1a.CreateSubscriptionRequest\x1a\x1b.CreateSubscriptionResponse\x12D\n" +
	"\x0fGetSubscription\x12\x17.GetSubscriptionRequest\x1a\x18.GetSubscriptionResponse\x12M\n" +
	"\x12UpdateSubscription\x12\x1a.UpdateSubscriptionRequest\x1a\x1b.UpdateSubscriptionResponse\x12M\n" +
	"\x12DeleteSubscription\x12\x1a.DeleteSubscriptionRequest\x1a\x1b.DeleteSubscriptionResponse\x12;\n" +
	"\fGetAnalytics\x12\x14.GetAnalyticsRequest\x1a\x15.GetAnalyticsResponseB\vZ\tpkg/protob\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_subscription_proto_goTypes = []any{
	(*Subscription)(nil),               // 0: Subscription
	(*Period)(nil),                     // 1: Period
	(*CreateSubscriptionRequest)(nil),  // 2: CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil), // 3: CreateSubscriptionResponse
	(*GetSubscriptionRequest)(nil),     // 4: GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),    // 5: GetSubscriptionResponse
	(*UpdateSubscriptionRequest)(nil),  // 6: UpdateSubscriptionRequest
	(*UpdateSubscriptionResponse)(nil), // 7: UpdateSubscriptionResponse
	(*DeleteSubscriptionRequest)(nil),  // 8: DeleteSubscriptionRequest
	(*DeleteSubscriptionResponse)(nil), // 9: DeleteSubscriptionResponse
	(*GetAnalyticsRequest)(nil),        // 10: GetAnalyticsRequest
	(*GetAnalyticsResponse)(nil),       // 11: GetAnalyticsResponse
}
var file_subscription_proto_depIdxs = []int32{
	0,  // 0: CreateSubscriptionResponse.sub:type_name -> Subscription
	0,  // 1: GetSubscriptionResponse.sub:type_name -> Subscription
	0,  // 2: UpdateSubscriptionResponse.sub:type_name -> Subscription
	1,  // 3: GetAnalyticsRequest.period:type_name -> Period
	0,  // 4: GetAnalyticsResponse.subs:type_name -> Subscription
	2,  // 5: SubscriptionService.CreateSubscription:input_type -> CreateSubscriptionRequest
	4,  // 6: SubscriptionService.GetSubscription:input_type -> GetSubscriptionRequest
	6,  // 7: SubscriptionService.UpdateSubscription:input_type -> UpdateSubscriptionRequest
	8,  // 8: SubscriptionService.DeleteSubscription:input_type -> DeleteSubscriptionRequest
	10, // 9: SubscriptionService.GetAnalytics:input_type -> GetAnalyticsRequest
	3,  // 10: SubscriptionService.CreateSubscription:output_type -> CreateSubscriptionResponse
	5,  // 11: SubscriptionService.GetSubscription:output_type -> GetSubscriptionResponse
	7,  // 12: SubscriptionService.UpdateSubscription:output_type -> UpdateSubscriptionResponse
	9,  // 13: SubscriptionService.DeleteSubscription:output_type -> DeleteSubscriptionResponse
	11, // 14: SubscriptionService.GetAnalytics:output_type -> GetAnalyticsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
